# Generated by Django 2.2.28 on 2024-03-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('top_genre', models.ManyToManyField(to='bookepedia.Genre')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, unique=True)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('cover', models.ImageField(blank=True, upload_to='book_covers')),
                ('slug', models.SlugField(unique=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookepedia.Genre')),
            ],
        ),
    ]
