# Generated by Django 2.2.28 on 2024-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
