# Generated by Django 2.2.28 on 2024-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='top_picks',
            field=models.ManyToManyField(blank=True, to='bookepedia.Book'),
        ),
    ]
