# Generated by Django 2.2.28 on 2024-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='book_covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
