# Generated by Django 2.2.28 on 2024-03-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0002_userprofile_top_picks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
