# Generated by Django 2.2.28 on 2024-03-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0003_auto_20240320_0835'),
        ('bookepedia', '0003_auto_20240319_1347'),
    ]

    operations = [
    ]
