# Generated by Django 2.2.28 on 2024-03-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0003_delete_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookinteraction',
            name='rating',
        ),
    ]
