# Generated by Django 2.2.28 on 2024-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0004_auto_20240309_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi')], default='Fantasy', max_length=128),
        ),
    ]
