# Generated by Django 2.2.28 on 2024-03-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookepedia', '0006_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookepedia.Genre'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='top_genre',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_genre',
            field=models.ManyToManyField(to='bookepedia.Genre'),
        ),
    ]
